### PR TITLE
Support for gf180mcuD

### PR DESCRIPTION
**Pull request by mole99**
It seems like support for gf180mcu is currently broken. I fixed up gf180mcuC and renamed it to gf180mcuD since this is the PDK which is currently used for the MPW shuttles.

The 8x32 RAM successfully builds:
`./dffram.py -p gf180mcuD -s gf180mcu_fd_sc_mcu7t5v0 -b ram 8x32`
But I seem to get a lot of hold violations. Well, better than nothing for now :)

I think it would make sense to add gf180mcu to the CI, so that support for it can't break that easily.

### CODE REVIEW

**Review by donn — APPROVED** [review]
Oh gosh. Sorry I missed this. Thank you so much.

**Comment by mole99** [comment]
No worries ^^
For my GFMPW-1 submission, I settled on the foundry provided SRAM in the end.

Nonetheless, it would be great to have proper support for gf180mcuD sometimes in the future 😃️

**Comment by donn** [comment]
I brought it up with the boss-- if he authorizes it we can look into adding the requisite buffering or what have you to get the hold violations out. But we're super busy as you can imagine… 🙃

**Comment by mole99** [comment]
I can imagine 😄️
Amazing things you and all the others at Efabless are creating!

**Pull request merged**
