### PR TITLE
Centralizing the core in case of forced minimum height

### PR DESCRIPTION
**Pull request by mohamedleithy**
Context: 
Centralizing the core in the die, after forcing min_height option. 

Change: Made the core height and die height independent of each other in case of min_height option, and centralized the core. 

Result:
Screen Shot 2022-02-22 at 9 53 07 PM

### CODE REVIEW

**Comment by mohamedleithy** [comment]
@antonblanchard

**Review by donn — APPROVED** [review]

**Comment by antonblanchard** [comment]
I tested this against the RAMs I am using, and it looks good. Thanks!

**Comment by antonblanchard** [comment]
Actually I think the met4 straps are not long enough. Let me get back to you.

**Comment by antonblanchard** [comment]
It doesn't solve the issue unfortunately. I asked for `--min-height 180` but it didn't resolve my met4 strap issues:

met4

**Comment by donn** [comment]
So wait, the straps are laid out only across the core area? That's silly. We'll take another look at PDN generation.

**Comment by antonblanchard** [comment]
@donn That does look to be the issue. I was going to increase the core area, but just getting the straps to extend past the core area sounds like a good solution.

**Pull request merged**
